package com.jw22.community.model;

public class Comment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.id
     *
     * @mbg.generated Wed Jun 24 16:31:45 CDT 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.parent_id
     *
     * @mbg.generated Wed Jun 24 16:31:45 CDT 2020
     */
    private Long parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.parent_type
     *
     * @mbg.generated Wed Jun 24 16:31:45 CDT 2020
     */
    private Integer parentType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.creator_id
     *
     * @mbg.generated Wed Jun 24 16:31:45 CDT 2020
     */
    private Long creatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.create_time
     *
     * @mbg.generated Wed Jun 24 16:31:45 CDT 2020
     */
    private Long createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.modify_time
     *
     * @mbg.generated Wed Jun 24 16:31:45 CDT 2020
     */
    private Long modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.up_vote
     *
     * @mbg.generated Wed Jun 24 16:31:45 CDT 2020
     */
    private Integer upVote;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.down_vote
     *
     * @mbg.generated Wed Jun 24 16:31:45 CDT 2020
     */
    private Integer downVote;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.description
     *
     * @mbg.generated Wed Jun 24 16:31:45 CDT 2020
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.reply_to
     *
     * @mbg.generated Wed Jun 24 16:31:45 CDT 2020
     */
    private Long replyTo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.id
     *
     * @return the value of comment.id
     *
     * @mbg.generated Wed Jun 24 16:31:45 CDT 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.id
     *
     * @param id the value for comment.id
     *
     * @mbg.generated Wed Jun 24 16:31:45 CDT 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.parent_id
     *
     * @return the value of comment.parent_id
     *
     * @mbg.generated Wed Jun 24 16:31:45 CDT 2020
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.parent_id
     *
     * @param parentId the value for comment.parent_id
     *
     * @mbg.generated Wed Jun 24 16:31:45 CDT 2020
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.parent_type
     *
     * @return the value of comment.parent_type
     *
     * @mbg.generated Wed Jun 24 16:31:45 CDT 2020
     */
    public Integer getParentType() {
        return parentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.parent_type
     *
     * @param parentType the value for comment.parent_type
     *
     * @mbg.generated Wed Jun 24 16:31:45 CDT 2020
     */
    public void setParentType(Integer parentType) {
        this.parentType = parentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.creator_id
     *
     * @return the value of comment.creator_id
     *
     * @mbg.generated Wed Jun 24 16:31:45 CDT 2020
     */
    public Long getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.creator_id
     *
     * @param creatorId the value for comment.creator_id
     *
     * @mbg.generated Wed Jun 24 16:31:45 CDT 2020
     */
    public void setCreatorId(Long creatorId) {
        this.creatorId = creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.create_time
     *
     * @return the value of comment.create_time
     *
     * @mbg.generated Wed Jun 24 16:31:45 CDT 2020
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.create_time
     *
     * @param createTime the value for comment.create_time
     *
     * @mbg.generated Wed Jun 24 16:31:45 CDT 2020
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.modify_time
     *
     * @return the value of comment.modify_time
     *
     * @mbg.generated Wed Jun 24 16:31:45 CDT 2020
     */
    public Long getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.modify_time
     *
     * @param modifyTime the value for comment.modify_time
     *
     * @mbg.generated Wed Jun 24 16:31:45 CDT 2020
     */
    public void setModifyTime(Long modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.up_vote
     *
     * @return the value of comment.up_vote
     *
     * @mbg.generated Wed Jun 24 16:31:45 CDT 2020
     */
    public Integer getUpVote() {
        return upVote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.up_vote
     *
     * @param upVote the value for comment.up_vote
     *
     * @mbg.generated Wed Jun 24 16:31:45 CDT 2020
     */
    public void setUpVote(Integer upVote) {
        this.upVote = upVote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.down_vote
     *
     * @return the value of comment.down_vote
     *
     * @mbg.generated Wed Jun 24 16:31:45 CDT 2020
     */
    public Integer getDownVote() {
        return downVote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.down_vote
     *
     * @param downVote the value for comment.down_vote
     *
     * @mbg.generated Wed Jun 24 16:31:45 CDT 2020
     */
    public void setDownVote(Integer downVote) {
        this.downVote = downVote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.description
     *
     * @return the value of comment.description
     *
     * @mbg.generated Wed Jun 24 16:31:45 CDT 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.description
     *
     * @param description the value for comment.description
     *
     * @mbg.generated Wed Jun 24 16:31:45 CDT 2020
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.reply_to
     *
     * @return the value of comment.reply_to
     *
     * @mbg.generated Wed Jun 24 16:31:45 CDT 2020
     */
    public Long getReplyTo() {
        return replyTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.reply_to
     *
     * @param replyTo the value for comment.reply_to
     *
     * @mbg.generated Wed Jun 24 16:31:45 CDT 2020
     */
    public void setReplyTo(Long replyTo) {
        this.replyTo = replyTo;
    }
}