package com.jw22.community.model;

public class Question {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.id
     *
     * @mbg.generated Mon Jun 22 22:48:21 CDT 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.title
     *
     * @mbg.generated Mon Jun 22 22:48:21 CDT 2020
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.description
     *
     * @mbg.generated Mon Jun 22 22:48:21 CDT 2020
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.createTime
     *
     * @mbg.generated Mon Jun 22 22:48:21 CDT 2020
     */
    private Long createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.modifyTime
     *
     * @mbg.generated Mon Jun 22 22:48:21 CDT 2020
     */
    private Long modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.creatorId
     *
     * @mbg.generated Mon Jun 22 22:48:21 CDT 2020
     */
    private Integer creatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.commentCount
     *
     * @mbg.generated Mon Jun 22 22:48:21 CDT 2020
     */
    private Integer commentCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.viewCount
     *
     * @mbg.generated Mon Jun 22 22:48:21 CDT 2020
     */
    private Integer viewCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.upVote
     *
     * @mbg.generated Mon Jun 22 22:48:21 CDT 2020
     */
    private Integer upVote;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.downVote
     *
     * @mbg.generated Mon Jun 22 22:48:21 CDT 2020
     */
    private Integer downVote;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.tag
     *
     * @mbg.generated Mon Jun 22 22:48:21 CDT 2020
     */
    private String tag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.id
     *
     * @return the value of question.id
     *
     * @mbg.generated Mon Jun 22 22:48:21 CDT 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.id
     *
     * @param id the value for question.id
     *
     * @mbg.generated Mon Jun 22 22:48:21 CDT 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.title
     *
     * @return the value of question.title
     *
     * @mbg.generated Mon Jun 22 22:48:21 CDT 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.title
     *
     * @param title the value for question.title
     *
     * @mbg.generated Mon Jun 22 22:48:21 CDT 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.description
     *
     * @return the value of question.description
     *
     * @mbg.generated Mon Jun 22 22:48:21 CDT 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.description
     *
     * @param description the value for question.description
     *
     * @mbg.generated Mon Jun 22 22:48:21 CDT 2020
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.createTime
     *
     * @return the value of question.createTime
     *
     * @mbg.generated Mon Jun 22 22:48:21 CDT 2020
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.createTime
     *
     * @param createTime the value for question.createTime
     *
     * @mbg.generated Mon Jun 22 22:48:21 CDT 2020
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.modifyTime
     *
     * @return the value of question.modifyTime
     *
     * @mbg.generated Mon Jun 22 22:48:21 CDT 2020
     */
    public Long getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.modifyTime
     *
     * @param modifyTime the value for question.modifyTime
     *
     * @mbg.generated Mon Jun 22 22:48:21 CDT 2020
     */
    public void setModifyTime(Long modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.creatorId
     *
     * @return the value of question.creatorId
     *
     * @mbg.generated Mon Jun 22 22:48:21 CDT 2020
     */
    public Integer getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.creatorId
     *
     * @param creatorId the value for question.creatorId
     *
     * @mbg.generated Mon Jun 22 22:48:21 CDT 2020
     */
    public void setCreatorId(Integer creatorId) {
        this.creatorId = creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.commentCount
     *
     * @return the value of question.commentCount
     *
     * @mbg.generated Mon Jun 22 22:48:21 CDT 2020
     */
    public Integer getCommentCount() {
        return commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.commentCount
     *
     * @param commentCount the value for question.commentCount
     *
     * @mbg.generated Mon Jun 22 22:48:21 CDT 2020
     */
    public void setCommentCount(Integer commentCount) {
        this.commentCount = commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.viewCount
     *
     * @return the value of question.viewCount
     *
     * @mbg.generated Mon Jun 22 22:48:21 CDT 2020
     */
    public Integer getViewCount() {
        return viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.viewCount
     *
     * @param viewCount the value for question.viewCount
     *
     * @mbg.generated Mon Jun 22 22:48:21 CDT 2020
     */
    public void setViewCount(Integer viewCount) {
        this.viewCount = viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.upVote
     *
     * @return the value of question.upVote
     *
     * @mbg.generated Mon Jun 22 22:48:21 CDT 2020
     */
    public Integer getUpVote() {
        return upVote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.upVote
     *
     * @param upVote the value for question.upVote
     *
     * @mbg.generated Mon Jun 22 22:48:21 CDT 2020
     */
    public void setUpVote(Integer upVote) {
        this.upVote = upVote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.downVote
     *
     * @return the value of question.downVote
     *
     * @mbg.generated Mon Jun 22 22:48:21 CDT 2020
     */
    public Integer getDownVote() {
        return downVote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.downVote
     *
     * @param downVote the value for question.downVote
     *
     * @mbg.generated Mon Jun 22 22:48:21 CDT 2020
     */
    public void setDownVote(Integer downVote) {
        this.downVote = downVote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.tag
     *
     * @return the value of question.tag
     *
     * @mbg.generated Mon Jun 22 22:48:21 CDT 2020
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.tag
     *
     * @param tag the value for question.tag
     *
     * @mbg.generated Mon Jun 22 22:48:21 CDT 2020
     */
    public void setTag(String tag) {
        this.tag = tag == null ? null : tag.trim();
    }
}